apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fedora-demo
  name: fedora-demo
spec:
  replicas: 10  # Some stress, which would still fit into 4G of swap
  selector:
    matchLabels:
      app: fedora-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fedora-demo
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - command:
          - bash
          - -c
          - " while [[ \"$(cat /sys/fs/cgroup/memory.swap.max)\" == \"0\" ]] ; do sleep 1 ; done ; stress -v -m 1 --vm-bytes 2G --vm-hang 1"
        image: >-
            quay.io/fdeutsch/wasp-operator-prototype:latest
        name: fedora
        resources:
          requests:
            cpu: "0.1"
          limits:
            memory: 0.5G
            node.kubevirt.io/swap: 1200
status: {}
