apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stress
  name: stress
spec:
  replicas: 10
  selector:
    matchLabels:
      app: stress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stress
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - command:
          - bash
          - -c
          - "while [[ \"$(cat /sys/fs/cgroup/memory.swap.max)\" == \"0\" ]] ; do sleep 1 ; done ; stress -v -m 1 --vm-bytes 2G"
        image: >-
            quay.io/fdeutsch/wasp-operator-prototype:latest
        name: fedora
        resources:
          requests:
#            cpu: "0.1"
            memory: 1G   # Minimum amount of memory for the wrkld
          limits:
            memory: 2.2G  # Give it space to burst in
            node.kubevirt.io/swap: 1200  ## ... but a backup in case of pressure
status: {}
