apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generateName: fedora-
spec:
  running: true
  template:
    spec:
      architecture: amd64
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
        memory:
          guest: 4G
        resources:   # Uncomment if you want to do manual overcommit
          limits:
            cpu: 0.02
          requests:
            memory: 500Mi
      terminationGracePeriodSeconds: 0
      volumes:
        - containerDisk:
            image: 'quay.io/containerdisks/fedora:39'
          name: containerdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitdisk
status: {}
