apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: static
  name: static
spec:
  replicas: 50
  selector:
    matchLabels:
      app: static
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: static
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - command:
          - bash
          - -c
          - "dd if=/dev/urandom of=/dev/shm/rnd bs=1M count=60 ; sleep inf"
        image: >-
            quay.io/openshift-virtualization/wasp-agent:latest
        name: fedora
        resources:
          requests:
            cpu: "0.01"
            memory: 1M
          limits:
            memory: 120M
status: {}
