apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stress
  name: stress
spec:
  replicas: 25
  selector:
    matchLabels:
      app: stress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stress
    spec:
      topologySpreadConstraints:
        - maxSkew: 5
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: stress
          matchLabelKeys:
            - pod-template-hash
      terminationGracePeriodSeconds: 0
      containers:
      - command:
          - bash
          - -c
          - "[[ \"$(cat /sys/fs/cgroup/memory.swap.max)\" == \"0\" ]] && exit 1 || stress -v -m 1 --vm-bytes 1G --vm-hang 3"
        image: >-
            quay.io/fdeutsch/wasp-operator-prototype:latest
        name: fedora
        resources:
          requests:
            cpu: "0.01"
            memory: 500M   # Minimum amount of memory for the wrkld
          limits:
            memory: 1.1G  # Give it space to burst in
status: {}
