apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stress
  name: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stress
    spec:
#      topologySpreadConstraints:
#        - maxSkew: 5
#          topologyKey: kubernetes.io/hostname
#          whenUnsatisfiable: ScheduleAnyway
#          labelSelector:
#            matchLabels:
#              app: stress
#          matchLabelKeys:
#            - pod-template-hash
      terminationGracePeriodSeconds: 0
      containers:
      - command:
          - bash
          - -c
          - "sleep $(( RANDOM % 30 )) ; stress -v -m 1 --vm-bytes 1G --vm-hang 3"
        image: >-
            quay.io/openshift-virtualization/wasp-agent:latest
        name: fedora
        resources:
          requests:
            memory: 50M   # Minimum amount of memory for the wrkld
          limits:
            cpu: "0.01"
            memory: 1.1G
status: {}
