name: Build and Push Image
on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['main']

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: wasp-agent
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile

  push-image-to-quay:
    name: Push image to quay.io
    needs: push-image
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'release' }}

    runs-on: ubuntu-latest
    steps:
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/openshift-virtualization
        username: openshift-virtualization+wasp_agent_gh_workflow
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
