name: lint

on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['main']

jobs:
  yaml:
    name: Lint yamls
    runs-on: ubuntu-latest

    steps:
      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: manifests

  bash:
    name: Lint bash scripts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: bash -n contrib/*
